# Generated by Django 4.2.6 on 2024-03-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photopost',
            old_name='Category',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='photopost',
            name='comment',
            field=models.TextField(blank=True, verbose_name='コメント'),
        ),
    ]
